name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - name: Print a message
            run: |
              echo "We are before actions/chechoutV2"
          - name: Check SSH Key
            run: |
              echo -e "$SSH_PRIVATE_KEY"
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > keyfile
              ssh -i keyfile -T git@github.com
            env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          - uses: actions/checkout@v2
          - name: Print a message
            run: |
              echo "We are after actions/chechoutV2"
          - name: Check SSH Agent Status
            run: |
              echo "Checking SSH agent status"
              ssh-agent -k
              eval $(ssh-agent -s)
              ssh-add -l
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
